create table days(
		id int identity(1,1) not null,
		day int not null
)

insert [dbo].[days] ([day]) values (01)
insert [dbo].[days] ([day]) values (02)
insert [dbo].[days] ([day]) values (03)
insert [dbo].[days] ([day]) values (04)
insert [dbo].[days] ([day]) values (05)
insert [dbo].[days] ([day]) values (06)
insert [dbo].[days] ([day]) values (07)
insert [dbo].[days] ([day]) values (08)
insert [dbo].[days] ([day]) values (09)
insert [dbo].[days] ([day]) values (10)
insert [dbo].[days] ([day]) values (11)
insert [dbo].[days] ([day]) values (12)
insert [dbo].[days] ([day]) values (13)
insert [dbo].[days] ([day]) values (14)
insert [dbo].[days] ([day]) values (15)
insert [dbo].[days] ([day]) values (16)
insert [dbo].[days] ([day]) values (17)
insert [dbo].[days] ([day]) values (18)
insert [dbo].[days] ([day]) values (19)
insert [dbo].[days] ([day]) values (20)
insert [dbo].[days] ([day]) values (21)
insert [dbo].[days] ([day]) values (22)
insert [dbo].[days] ([day]) values (23)
insert [dbo].[days] ([day]) values (24)
insert [dbo].[days] ([day]) values (25)
insert [dbo].[days] ([day]) values (26)
insert [dbo].[days] ([day]) values (27)
insert [dbo].[days] ([day]) values (28)
insert [dbo].[days] ([day]) values (29)
insert [dbo].[days] ([day]) values (30)
insert [dbo].[days] ([day]) values (31)